app:
  version: @project.version@
  buildtime: @maven.build.timestamp@
  pooled-db: true
  datasource:
    h2datasource:
      url: jdbc:mysql://localhost:3306/weather
      username: root
      password: ${MySQL-PASSWORD}
      configuration:
        pool-size: 30
    cache-db:
      url: jdbc:mysql://localhost:3306/weather
      username: root
      password: ${MySQL-PASSWORD}
      configuration:
        pool-size: 30
server:
  port: 2122

retrofit:
  integration:
    cacheSizeInMb: 50
    cacheDirectory: "retrofit/cache"
    longRunningReadTimeout: 1000
  endpoints:
    - serviceName: OpenWeatherMap_currentWeather_API
      baseUrl: https://api.openweathermap.org/data/2.5/
      path: weather
      weatherUnit: metric
      apiKey: ${OpenWeatherMap_API_key}
    - serviceName: OpenWeatherMap_hourlyWeather_API
      baseUrl: https://pro.openweathermap.org/data/2.5/forecast/
      path: hourly
      weatherUnit: metric
      apiKey: ${OpenWeatherMap_API_key}
    - serviceName: OpenWeatherMap_dailyWeather_API
      baseUrl: https://api.openweathermap.org/data/2.5/forecast/
      path: daily
      weatherUnit: metric
      apiKey: ${OpenWeatherMap_API_key}

spring:
  jpa:
    database: default
  flyway:
    out-of-order: false
    ignore-future-migrations: true
    ignore-ignored-migrations: true
    ignore-missing-migrations: true
    baseline-on-migrate: true
    location: classpath:/db/migration/
  datasource:
    url: jdbc:mysql://localhost:3306/weather
    username: root
    password: ${MySQL-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
